### PR TITLE
Fix duplicate words and typos in multiple markdown files

### PR DESCRIPTION
**Pull request by yusi1**
Did some grepping and found some duplicate words

### CODE REVIEW

**Comment by yusi1** [comment]
Sorry for the commits showing up as multiple users, I must have configured another Github account with a different email address at some point.

**Review by yusi1 — COMMENTED** [review]
Is a full stop meant to be there in https://github.com/bedrocklinux/bedrocklinux-website/commit/5a3b836bf6a1693f36d945e0c564bb43b3044db0, or should I just revert it aswell? @paradigm

**Comment by yusi1** [comment]
Squashed and re based the commits into one.

**Comment by yusi1** [comment]
> Is a full stop meant to be there in [5a3b836](https://github.com/bedrocklinux/bedrocklinux-website/commit/5a3b836bf6a1693f36d945e0c564bb43b3044db0), or should I just revert it aswell? @paradigm

Can't revert now since I rebased and squashed.

**Comment by yusi1** [comment]
@paradigm

**Comment by cptpcrd** [comment]
> Is a full stop meant to be there in [5a3b836](https://github.com/bedrocklinux/bedrocklinux-website/commit/5a3b836bf6a1693f36d945e0c564bb43b3044db0), or should I just revert it aswell? @paradigm

I'm not a Bedrock maintainer, but to me it looks like it was intentional (the surrounding bullets also end with full stops).

> @paradigm can you merge this PR?

I'm sure he'll take a look when he gets a chance, but he does have a life. Please be patient.

**Pull request closed without merging**
